module.exports = {
  // Safelisting some classes to avoid content purge
  plugins: [require('daisyui')],
  safelist: [
    'safelisted',
    'bg-primary',
    'bg-secondary',
    'bg-accent',
    'bg-neutral',
    'bg-base-100',
    'bg-base-200',
    'bg-base-300',
    'bg-base-content',
    'bg-info',
    'bg-success',
    'bg-warning',
    'bg-error',
  ],
  daisyui: {
    themes: [
      ...Object.keys(require('daisyui/src/theming/themes')),
      {
        legacy: {
          primary: '#2980b9',
          secondary: '#7028b8',
          accent: '#b87a28',
          neutral: '#999',
          info: '#2980b9',
          success: '#27ae60',
          warning: '#e67e22',
          error: '#c0392b',
          'base-100': '#41444f',
          'base-200': '#999',
          'base-300': '#30333b',
          'base-content': '#fff',
          'primary-content': '#fff',
          'secondary-content': '#fff',
          'accent-content': '#fff',
          'neutral-content': '#fff',
          'info-content': '#fff',
          'success-content': '#fff',
          'warning-content': '#fff',
          'error-content': '#fff',
          '--rounded-box': '0rem',
          '--rounded-btn': '0rem',
        },
      },
    ],
  },
}
